### ISSUE TITLE
There is 3 copies of M2

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II-SRX/profile_collection#4]
1

https://github.com/NSLS-II-SRX/profile_collection/blob/34b25c4ae38b6aca5e98f0f88c0d15d8a487b718/startup/05-endstation.py#L12-L21 https://github.com/NSLS-II-SRX/profile_collection/blob/34b25c4ae38b6aca5e98f0f88c0d15d8a487b718/startup/05-endstation.py#L35

2

https://github.com/NSLS-II-SRX/profile_collection/blob/34b25c4ae38b6aca5e98f0f88c0d15d8a487b718/startup/05-endstation.py#L24-L32
https://github.com/NSLS-II-SRX/profile_collection/blob/34b25c4ae38b6aca5e98f0f88c0d15d8a487b718/startup/05-endstation.py#L36

3

https://github.com/NSLS-II-SRX/profile_collection/blob/34b25c4ae38b6aca5e98f0f88c0d15d8a487b718/startup/15-optics.py#L177-L183

Note that 3 over-write 1.

We probably should consolidate this to just 1 class and 1 instance.

**Comment by andrewmkiss** [comment]
I've been meaning to go through the startup scripts and clean them up. I think this class and device can be deleted, as they were part of the old KB system that is not in use anymore. I will confirm this. Also, I want to do some cleanup so I will start to do this and pushing to master.

**Comment by andrewmkiss** [comment]
This should be taken care of in the "cleanup" pull.

**Comment by mrakitin** [comment]
This was resolved by @andrewmkiss during the recent rewrite.
